version: '3'

services:
  db:
    container_name: "loan_db"
    image: mysql:8.0.36
    ports:
      - '3307:3306'
    env_file:
      - .docker_env
    volumes:
      - loan_db_vol:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]

  redis:
    container_name: "loan_redis"
    image: redis:6.0
    ports:
      - '6378:6379'
    volumes:
      - redisdata:/data

  server:
    container_name: "loan_server"
    build: .
    expose:
      - "8000"
    env_file:
      - .docker_env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  celery:
    container_name: "loan_celery"
    build: .
    command: celery -A config -l info
    volumes:
      - .:/app
    env_file:
      - .docker_env
    depends_on:
      - redis
      - server
volumes:
  loan_db_vol:
  redisdata:
