# Generated by Django 4.2.10 on 2024-02-14 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
        ('loan_management', '0002_alter_loandata_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandata',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customer_management.customerdata'),
        ),
    ]
